css/style.css
index.php

Change log:
- Font scaling and section padding in IE 11 is fixed by replacing 'vmax' with '1vw + 1vh - 1vmin'.
- Fixed navbar position when scrolling.
- Fixed stack exchange link in the footer.
- Removed repeated 'Afrikaans' word in language selector.
- Added a small credit in the footer ;)

Fix font scaling and padding in IE 11 and other changes.

---

updatefromcrowdin.py

[flake8](http://flake8.pycqa.org) testing of https://github.com/FreeCAD/FreeCAD-Homepage on Python 3.7.1
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./updatefromcrowdin.py:93:21: E999 SyntaxError: invalid syntax
print "language:",lncode
^
1     E999 SyntaxError: invalid syntax
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- …

Use print() function in both Python 2 and Python 3

---

tracker/plugins/FreecadTheme/freecad.js

Bugtracker has a new field called `FreeCAD Information`. It is a multiline text field that is evaluated against a regex ([test regex](https://regex101.com/r/sxfalb/4)). 
`^([A-Z][\w\ ]+)\:\ ([\w\ \(\)\/\\\.\-]+)$
`
You can view the details on MantisBT at https://freecadweb.org/tracker/manage_custom_field_edit_page.php?field_id=1 
If a user submits a ticket without adding their FC info, the ticket will not submit and will ask them to do so. All they need to do is hit back button in their browser (their ticket info will not be lost).
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=8&t=40108

Bugtracker: Add help text to new FC Info custom field 

---

downloads.php

A small esthetic commit that makes it easier to find relevant download links within the download.php file

downloads.php: distinguish html source so it's easier to find links

---

downloads.php

The old link was pointing to the stable version for MacOS, which I guess doesn't exist? So I replaced it with a working link to the pre_19 MacOS version, which is what the version 18 download page tells mac users to use.

Fixed Broken MacOS Link on Downloads.php

---

downloads.php
index.php

i just stumbled upon the link to the freecad room on  matrix.org and saw that it still goes to riot.im. the new name is element.io

change riot to element

---

index.php

There is no change when the "floating arrow" on Home page is hovered by the user. 
Users may not realize that the button is clickable and miss the intended action. Changing the mouse pointer to a finger pointer on hover can enhance the user experience by providing clear and consistent feedback.
**Current behaviour-**
**After changes** 
Converts the "mouse pointer" to "finger pointer" for the "floating arrow" on home page.
Remove the floating arrow button to simplify the user interface and avoid irrelevant elements on the screen.

Added onmousehover style to home page.

---

footer.php

Implemented a "Improve this page on github" link in the footer section of every webpage, directing users to their respective source files in GitHub `https://github.com/FreeCAD/FreeCAD-Homepage`. 
This feature enables users to easily fork and edit the content of webpages on GitHub.
Screenshot -

feat: Added GitHub Edit Links

---

downloads.php

Two major changes: the download buttons are now doubled, so that on Mac OS and Linux we can provide downloads for two architectures, and on Windows we can provide an installer and a standalone 7-zip download.
Second: the language about running the development versions was changed to reflect the expected challenges we face in the upcoming dev cycle when merging the Toponaming code. Normal users are no longer encouraged to run a development version, and even advanced users should exercise caution and not use the development version in a production environment.

Update for 0.21.0 release

---

header.php

Hi !
Here is a small update to header.php to include a link for people interested to help in translations/localisation.
The change included in this first commit is a link to the FreeCAD wiki page that has some informations about translations in FreeCAD overall (rather than a direct link to Crowdin).
Another option to discuss, proposed by @kaktusus, is to create a new page for the website, as a welcome place for new translators that could provide an in-depth description of the translation of various aspects of the FreeCAD ecosystem (GUI, docs, manual, Wiki, website, etc.), first in general and then in more detail.
What do you think ?
Note that this PR is the 2nd attempt and replaces the previous one of yesterday XD (sorry for the noise, still learning...)

Add header link to help for translations/localisation

---

thankyou.php

There were two spaces between "to" and "more", so the typo I noticed appears to have meant to have an additional word, rather than e.g. change "to" to "for", for "for more options" which would also fit.

Update thankyou.php, "to  more options" -> "to see more options"

---

css/style.css

Fix Navigation item spacing

---

contrib/addon_github_stats.py

The server is still running Python 3.7, so tweak the type hinting.

Fix type hinting for Python 3.7

---

contrib/addon_github_stats.py

Not yet supported, and the version of python-gitlab on the server is out of date.

Disable Gitlab checks

---

downloads.php

The current "development" section of the [downloads page](https://www.freecad.org/downloads.php) lists obsolete entries (homebrew, that does not have a dev version), and confusing entries (conda, which actually all link to the same location). This PR simplifies that:
Before:
After:

Reformatted development builds section

---

index.php

There is no screenshot of Bootstrap's tooltip feature being implemented to show image credits because it is not something that can be screenshotted. You can look at it [here](https://cizgivedizi.com/FreeCAD-Homepage/). The credits have been added in this way and can be changed.
My favorite part about this change is that it adds almost nothing.

Sisyphus Touch: Displaying image credits as tooltips

---

downloads.php

only the libfuse2 package is required in ubuntu, the fuse package conflicts with other important packages and if you don't read carefully and accept the installation you could break your desktop environment, see https://forum.freecad.org/viewtopic.php?p=761401

Update fuse comment about appimages

---

footer.php

Since these are now moved directly to the images, there is no need for something like this to appear on every page.

Removing image credits on footer

---

features.php

https://github.com/FreeCAD/FreeCAD-Homepage/pull/178#issuecomment-2260343501 I mentioned this in the past and suggested a solution to this, but since the solution I suggested was not accepted, I left it as it is. However, upon the requests of @hyarion and @maxwxyz on discord, I am making the same change again. You can look [here](https://cizgivedizi.com/FreeCAD-Homepage/features.php).
<details>
<summary>Screenshots</summary>
Before:
After:
</details>
It is worth remembering that this is not magic, so the change will not give the perfect appearance, but it will ensure that the images do not look stretched. This means they always maintain their aspect ratio.

Sisyphus Touch: Fix to the Image Streched Problem on the Features Page

---

css/style.css

I saw a new sponsor sharing this screen in a [post](https://x.com/GenysysEngine/status/1865689842119573968) on Twitter. This is definitely an annoying thing. This is the only way it can be fixed with minimal hoeing. That's the beauty and curse of Open Source: actually, if there's something you don't like, you can change it.
Before:
After:

Sisyphus Touch: Keeping sponsors in line

---

css/style.css
donation.php

In the old logic, onclick logic in html, the codes were nested within html, now eventlistener is used instead, this allows for easy changes without entering html. Also, the functions were edited for future reusability. Precautions were taken against multiple elements with the same id on the page. Opencolective için sponsorluk bağlantısı düzeltildi. Also, a small number value in one of the previous PRs was corrected.
These changes are mostly forward-looking because it is easier to make changes to the design this way. Also, eventlisteners are necessary for doing more complex things.

Sisyphus Revision:Changing the logic of the donation code

---

header.php

There are social links under Community. Since we have no information about whether these were used or not, I guess they were not used(I wish there was something on the site where we would know exactly what was and wasn't used.).In general, social links are not given in this way, they are given in the footer anyway, which is given in our case. Additionally, they were preventing you from accessing the calendar from the menu on mobile. This problem has now been resolved.

Community Cleaning

---

telemetry.php

Adds a filter function for the stats to translate stats so it is easier to read:
* Python version is now used and reported as 3.11 instead of just 11 (This also handles if python 4 is ever released)
* `darwin` is reported for macOS users. This replaces `darwin` with `macOS`

Telemetry: Make python version and system stats easier to read

---

posthog-event-fetcher.php

Mirrors the new entries in the `navigational_orbit_style` enum in https://github.com/FreeCAD/FreeCAD/pull/20535/files#diff-c63394a30dfe22f21f8ae192e0d321503c9c85f3b03c5f7bd23c589b9d330ea0R67-R69
Note, as no one seems to be using these styles with the telemetry addon, it's quite difficult to test, so I just made the changes in the GH interface without testing it.
I've doubled and triple checked the syntax and values.

Telemetry: Add new orbit styles

---

donation.php

OpenCollective's tax deduction status is not relevant, they are not our project's Fiscal Host (that is the Open Source Collective). And *that* collective is a 501(c)(6) not-for-profit, which is quite different. We should not make any statements about the potential tax implications of donating to the project, that is going to be up to the individual and their accountant: generally speaking, these donations are *not* tax deductible for individuals.

Remove reference to OpenCollective tax status
