FreeCAD/FreeCAD-Homepage

css/freecad.css

Fix responsive footer position

---

wiki/skins/freecad/style.css

Move placeholder text to sidebar warning

---

tracker/plugins/FreecadTheme/freecad.css

Remove Mantis FC CSS workaround for resolved tickets line-through

---

.htaccess

Discussion:
https://forum.freecadweb.org/viewtopic.php?f=8&t=26599

Add Expires headers and unset ETags

---

downloads.php

Updated from `r16110` to `r16117`
CC @sgrogan

Update to 0.18.2 download links

---

downloads.php

* Updated all download links to v0.18.3  
* Added minor version to page header

Bump to FC v0.18.3

---

tracker/plugins/FreecadTheme/freecad.js

Fix previous commit

---

downloads.php
forum/styles/freecad/template/overall_header.html
index.php
tracker/plugins/FreecadTheme/freecad.js

Update across all of the frameworks in this repo

Update www.freecadweb.org/wiki to wiki.freecadweb.org

---

index.php

Remove mention of youtube from footer

---

downloads.php

Update macOS and AppImage URLS

---

forum/styles/freecad-dark/theme/_common.scss
forum/styles/freecad/theme/_common.scss

Closes #61  
Fix was copied from the phpbb Elegance theme that comes bundled with phpbb

Forum: fix emoji size on all FreeCAD phpbb themes 

---

downloads.php

Removed windows 32bit link  
Added v0.20_pre as new devel tag (even though it's not officially been tagged.

Updated download page links to new 0.19.1 stable

---

downloads.php
index.php

Homepage: Change matrix link

---

downloads.php
index.php

Option to connect to FreeCAD on Freenode IRC via webchat

Homepage: Add freenode webchat IRC link

---

downloads.php

Ref: https://github.com/FreeCAD/FreeCAD-Bundle/issues/63

Homepage: fix macOS minimum version to 10.12

---

features.php

removed leftover anchor terminator fragment (line#243). added double quotes for attribute href values where missing (minor rearrangement of an 'and' to make each of those stand out and it looked lost). gave some http links some s' where applicable.

minor corrections to features.php

---

features.php

The other mention is on line 209.

Remove double mention of STL in features.php

---

themes/forum/styles/freecad/template/overall_header.html

Change link from .../images/logo.png to .../svg/logo-freecad.svg/

---

thankyou.php

h/t to fandaL for the heads-up

Website: fix incorrect link to FC 'Getting started' wiki page

---

header.php

Update Discord link to a never-expire link

---

css/style.css

Improved the Navbar by adding a backdrop which make the background bit of glassy.

Website: Add blur effect to navbar

---

footer.php

Since the discord link in the footer wasn't working, I updated it with the current one.
[Old link](https://discord.com/invite/NpMefpXWFT)
[New Link](https://discord.com/invite/w2cTKGzccC)

Footer Discord link updated.

---

thankyou.php

As suggested on Discord by ThothLoki.

Correct the wording order of "go further, faster"

---

features.php
index.php

- changed 'multiplatfom' to 'multiplatform'
- removed an extra 'and'

Fixed a couple typos in the website text

---

downloads.php

fixes FreeCAD/FreeCAD-translations#279

Untranslate version number

---

donation.php
lang/homepage.pot
themes/wiki/skins/freecad/freecad.skin.php

Fix capitalization of GitHub.

---

downloads.php
features.php

fixes FreeCAD/FreeCAD-translations#280

Translation fixes

---

downloads.php

Hi !
Please, merge Yorik's PR first.
Thank you !

update downloads.php with more translatable wiki links

---

contrib/addon_github_stats.py

Relies on the server having a GitHub access token installed.

Contrib: Add script that creates addon stats

---

contrib/addon_github_stats.py

Similar to list, to support Py 3.7

Fix type hinting for dictionaries

---

header.php

Fixes what can be fixed of https://github.com/FreeCAD/FreeCAD-translations/issues/293

Translate links that can be translated

---

contrib/addon_cache.py

Addon cache got stale because checkout doesn't do a merge.

Add missing git merge

---

downloads.php
features.php

I'm adding 1.0 to the relevant places on the site. Actually, I waited for the artifacts to be created, but I couldn't stand sleeping, so I gave possible links to the relevant links. But considering the way it was created, it's probably okay. I guess there is nothing I missed.
If there are errors in the links, please change them. You can follow the process [here](https://github.com/FreeCAD/FreeCAD/releases/tag/1.0.0).

All Hail the 1.0

---

index.php

https://github.com/FreeCAD/FreeCAD-Homepage/pull/207#issuecomment-2486216192

What's new in 1.0?

---

blog.php
css/style.css
downloads.php
events.php
features.php
index.php
sponsor.php

https://github.com/FreeCAD/FreeCAD-Homepage/pull/178 I created the btn class this way, thinking that this was the shortest way, and it still is, but I think this solution is more correct. It doesn't change anything visually.

Correction of btn class

---

telemetry.php

Legends no longer appear in the bar charts and percentages are calculated according to the number of users, and the loader appears when loading the charts.

Fixes and Additions to Telemetry Charts

---

telemetry.php

Adds relevant information and a video showing how to install it at the top of the Telemetry page.

Adding Telemetry Info

---

posthog-event-fetcher.php

For the previous fetcher, it was pulling all events without any filters. This can be done for a certain number of users, but as the number of users increases, the file size increases a lot. By changing this, the user's last event is taken from each event type. The file size and the number of requests sent are greatly reduced.

Telemetry Fetcher Optimization

---

telemetry.php

Shrinks down screen res panel to make it use only one column

Telemetry: Add FreeCAD version

---

telemetry.php

When I made changes, I forgot to make some parts suitable for the translation system, this PR provides it.

Making Some Parts of Telemetry Translatable

---

posthog-event-fetcher.php
telemetry.php

- Fetch from posthog if fetcher is newer than datafile
- Update chart data source to use local file
- Add optional caching of posthog queries for testing
- Add FreeCAD version
- Use Python major and minor version instead of just minor
- Add data filtering and sanitization
- Filter out empty labels

Telemetry: Add back lost features

---

index.php

This unifies the header styles in the sections.
Notice the difference in circled areas.

Remove capitalization in new headers

---

translation.php

Fix: #276
Already have the file, I don't think it will cause any problems.
@luzpaz @yorikvanhavre

add Swedish on Menu

---

thankyou.php

I've rewritten the support FreeCad section on this page for readability as there were a few sentences that didn't scan particularly well. Hope it's of use.

Update thankyou.php readability of support us section

---

downloads.php

Part of https://github.com/FreeCAD/FreeCAD/issues/22803
Clarifies where archived weekly builds can be downloaded.

Download: update link to weekly builds

---

addons.php

Actually, I always wanted to do this, but telemetry intervened and I postponed it, I am not satisfied with the style, but it shows all addons instantly by pulling them from the same source as addonmanager, moreover, when you press on it, it goes to the relevant address, in fact, there are a lot of links, but I didn't know where to put them. I tried something different for the icons.
For now, it is in alphabetical order, but in the future it can use the order taken from telemetry.
As always, you can check it out at this [link](https://cizgivedizi.com/FreeCAD-Homepage/addons.php).

SR: A Simple Page for Addons

---

translation.php

Vulnerability reported here: 
https://www.openbugbounty.org/reports/2758953/
https://www.openbugbounty.org/reports/3194779/
https://www.openbugbounty.org/reports/3353526/
https://www.openbugbounty.org/reports/3852878/
https://www.openbugbounty.org/reports/3950002/
https://www.openbugbounty.org/reports/4033993/
I'd bet that all of the "On hold" vulnerabilities at OpenBugBounty are all the same thing, they don't seem to filter for duplicates.

Fix XSS vulnerability in translation code

---

professional-network.php

Some large gaps have been reduced in size to resemble other parts of the site.

Some styling for professional-network page
